sudo: required

services:
  - docker

language: node_js

node_js:
  - '6'
  - '8'
  - '9'

before_install:
  - docker pull tile38/tile38:1.11.1
  - docker run -d --net=host tile38/tile38:1.11.1
  - docker ps -a

script:
  - export TILE38_PORT=9851
  - env
  - npm run test

after_script:
  - npm run cvrg
