sudo: required

services:
  - docker

language: node_js

node_js:
  - '6'
  - '8'
  - '9'

before_script:
  - env

before_install:
  - docker pull tile38/tile38:1.11.1
  - docker run -d --net=host tile38/tile38:1.11.1
  - docker ps -a

script:
  - npm run test
